### ISSUE TITLE
Namespace for the Pinterest SocialiteProvider is invalid

### ISSUE THREAD

**Issue by mystus** [SocialiteProviders/Pinterest#2]
In both the PinterestExtendSocialite.php as well as the Provider.php files, the namespace needs to be changed from

`namespace SocialiteProviders\PinterestSocialite;`

to

`namespace SocialiteProviders\Pinterest;`

in order for this provider to work correctly.

**Comment by DraperStudio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this?

**Comment by mystus** [comment]
More than happy to.
